spring.datasource.url=jdbc:mysql://localhost:3306/cityworks_db
spring.datasource.username=root
spring.datasource.password=Mitrajit@12345
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8087

# Logging level
logging.level.root=INFO
logging.level.com.cityworks=DEBUG

# Log file output
logging.file.name=logs/cityworks.log

# Log format (console)
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %level - %logger{36} - %msg%n